name: Node.js Express
version: 0.4.1
description: Express web framework for Node.js with helmet
license: Apache-2.0
language: nodejs
maintainers:
  - name: Srini Paspunoori
    email: spaspunoori@gmail.com
    github-id: spaspunoori
default-template: simple
requirements:
  docker-version: ">= 17.09.0"
  appsody-version: ">= 0.2.7"
